### ISSUE TITLE
can't make element center, must specify position absolute in css ?

### ISSUE THREAD

**Issue by crapthings** [dreamerslab/jquery.center#3]
is this a bug ?

i make a div#splash and

$('#splash').center()

i can see it sets other properties to #splash

but it doesn't make it center, until i set position: absolute to #splash.

v1.1.0

**Comment by ben-lin** [comment]
Yes, this plugin only works for absolute elements.

**Comment by crapthings** [comment]
i think this should provide an option. if we use center plugin why we had to write separate code.

**Comment by ben-lin** [comment]
Because if it's not an absolute element. It might break things. For example with float elements the layout would be totally different. I should have add this info on readme.
